/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.PSC.SGR.Apresentacao;

import br.edu.ifnmg.PSC.SGR.Aplicacao.Compromisso;
import br.edu.ifnmg.PSC.SGR.Aplicacao.Fornecedor;
import br.edu.ifnmg.PSC.SGR.Aplicacao.Individuo;
import br.edu.ifnmg.PSC.SGR.Aplicacao.ViolacaoRegraNegocioException;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DONO
 */
public class CompromissoIndividuoBuscar extends javax.swing.JInternalFrame {

    public Compromisso compromisso;
    public CompromissoIndividuoBuscar(Compromisso compromisso) {
        initComponents();
        
        this.compromisso=compromisso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusca = new javax.swing.JTable();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setTitle("Envolvidos");

        tblBusca.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        tblBusca.setForeground(new java.awt.Color(51, 51, 51));
        tblBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBusca);

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnEditar.setText("Viz./Edit.");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnDeletar)))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar)
                    .addComponent(btnDeletar))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        CompromissoIndividuoEditar compromissoIndividuoEditar = new CompromissoIndividuoEditar();
        
        compromissoIndividuoEditar.setTelaMae(this);

        this.getParent().add(compromissoIndividuoEditar);
        
        compromissoIndividuoEditar.centraliza();
        
        compromissoIndividuoEditar.setVisible(true);

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(retornaIdSelecionado()!=-1){
            CompromissoIndividuoEditar compromissoIndividuoEditar = new CompromissoIndividuoEditar(retornaIdSelecionado());

            compromissoIndividuoEditar.setTelaMae(this);

            this.getParent().add(compromissoIndividuoEditar);

            compromissoIndividuoEditar.centraliza();

            compromissoIndividuoEditar.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(retornaIdSelecionado()!=-1){
            compromisso.removeIndividuo(retornaIdSelecionado());
            preencheTabela();
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    public int retornaIdSelecionado() {
        int linha=tblBusca.getSelectedRow();

        if(linha==-1)
            return linha;
        
        linha = tblBusca.convertRowIndexToModel(linha);
        int id = Integer.parseInt( tblBusca.getModel().getValueAt(linha, 0).toString() );
        return id;
    }

    public void preencheTabela(){
        
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int linha, int coluna) {  
                return false;
            }  
        };
        
        // Table Model 
        // Informa quais as colunas da tabela
        
        modelo.addColumn("ID");
        modelo.addColumn("Tipo");
        modelo.addColumn("Nome");
        
        // Adiciona as linhas da tabela
        
        for(Integer s : compromisso.getListaIndividuos()){
            Individuo i = null;
            try {
                Vector linha = new Vector();
                linha.add(s);
                i = Repositorios.getClienteRepositorio().Abrir(s);
                if(i!=null)
                    linha.add("Cliente");
                else{
                    linha.add("Fornecedor");
                    i = Repositorios.getFornecedorRepositorio().Abrir(s);
                }
                linha.add(i.getNome());
                modelo.addRow(linha);
            } catch (ViolacaoRegraNegocioException ex) {
                Logger.getLogger(CompromissoIndividuoBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        tblBusca.setModel(modelo);
        
        tblBusca.setAutoCreateRowSorter(true);
        
        tblBusca.getColumnModel().removeColumn( tblBusca.getColumnModel().getColumn(0));  

        tblBusca.getRowSorter().toggleSortOrder(1);  

        tblBusca.setRowHeight(27);
        
    }
    
    public void centraliza() {
        Dimension d = this.getParent().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusca;
    // End of variables declaration//GEN-END:variables
}
