/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.PSC.SGR.Apresentacao;

import br.edu.ifnmg.PSC.SGR.Aplicacao.Email;
import br.edu.ifnmg.PSC.SGR.Aplicacao.PedidoProduto;
import br.edu.ifnmg.PSC.SGR.Aplicacao.PedidoProdutoRepositorio;
import br.edu.ifnmg.PSC.SGR.Aplicacao.PedidoRecebido;
import br.edu.ifnmg.PSC.SGR.Aplicacao.Repositorio;
import br.edu.ifnmg.PSC.SGR.Aplicacao.ViolacaoRegraNegocioException;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DONO
 */
public class PedidoRecebidoBuscar extends TelaBusca<PedidoRecebido>{

    /**
     * Creates new form PedidoRecebidoBuscar
     */
    public PedidoRecebidoBuscar(Repositorio<PedidoRecebido> repositorio, Class tipo_tela) {
        super(repositorio, tipo_tela);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusca = new javax.swing.JTable();

        setTitle("Pedido Recebido");

        tblBusca.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        tblBusca.setForeground(new java.awt.Color(51, 51, 51));
        tblBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBusca);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public int retornaIdSelecionado() throws ViolacaoRegraNegocioException{
        int linha=tblBusca.getSelectedRow();

        if(linha==-1)
            return linha;
        
        linha = tblBusca.convertRowIndexToModel(linha);
        int id = Integer.parseInt( tblBusca.getModel().getValueAt(linha, 0).toString() );
        return id;

    }

    @Override
    public HashMap<String, String> preencheFiltro(HashMap<String, String> filtroPreDeterminado) {
        return filtroPreDeterminado;
    }

    @Override
    public void preencheTabela(List<PedidoRecebido> listagem) {
        // Table Model 
        
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int linha, int coluna) {  
                return false;
            }  
        };
        
        // Informa quais as colunas da tabela
        
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Valor");
        
        // Adiciona as linhas da tabela
        PedidoProdutoRepositorio pedidoprodutoRepositorio=Repositorios.getPedidoProdutoRepositorio();
        
        
        for(PedidoRecebido s : listagem){
            try {
                Vector linha = new Vector();
                linha.add(s.getId());
                linha.add(s.getCliente().getNome());
                HashMap<String,String> pedido=new HashMap<>();
                pedido.put("pedido", Integer.toString(s.getId()));
                List<PedidoProduto> listaProdutos=pedidoprodutoRepositorio.Buscar(pedido);
                float total = 0;
                for(PedidoProduto p: listaProdutos)
                    total+=p.getProduto().getCusto()+p.getProduto().getLucro();
                linha.add(total);
                
                modelo.addRow(linha);
            } catch (ViolacaoRegraNegocioException ex) {
                Logger.getLogger(PedidoRecebidoBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        tblBusca.setModel(modelo);
        
        tblBusca.getColumnModel().removeColumn( tblBusca.getColumnModel().getColumn(0));  
        
        tblBusca.setAutoCreateRowSorter(true);

        tblBusca.getRowSorter().toggleSortOrder(1);          
        
        tblBusca.setRowHeight(27);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBusca;
    // End of variables declaration//GEN-END:variables
}
