/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.PSC.SGR.Apresentacao;

import br.edu.ifnmg.PSC.SGR.Aplicacao.Email;
import br.edu.ifnmg.PSC.SGR.Aplicacao.Usuario;
import br.edu.ifnmg.PSC.SGR.Aplicacao.ViolacaoRegraNegocioException;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.SimpleEmail;

/**
 *
 * @author DONO
 */
public class Resgatar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Resgatar
     */
    public Resgatar() {
        initComponents();
        this.setClosable(true);
        this.setMaximizable(true);    
        getRootPane().setDefaultButton(btnEnviar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxSenha = new javax.swing.JCheckBox();
        cbxLogin = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        setTitle("Resgatar");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Email");

        cbxSenha.setSelected(true);
        cbxSenha.setText("Senha");
        cbxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSenhaActionPerformed(evt);
            }
        });

        cbxLogin.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Resgatar");

        btnEnviar.setText("Enviar Email");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxLogin)))
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxSenha)
                    .addComponent(cbxLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSenhaActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if(cbxLogin.isSelected() || cbxSenha.isSelected()){
            try {
                HashMap<String,String> filtro=new HashMap<>();
                filtro.put("email",txtEmail.getText());

                boolean cadastrado=false;

                List<Email> resultadoEmail=Repositorios.getEmailRepositorio().Buscar(filtro);

                if(!resultadoEmail.isEmpty()){
                    filtro.clear();
                    filtro.put("individuo",Integer.toString(resultadoEmail.get(0).getIndividuo()));
                    List<Usuario> resultadoUsuario=Repositorios.getUsuarioRepositorio().Buscar(filtro);
                    if(!resultadoUsuario.isEmpty()){
                        cadastrado=true;
                        try {
                            resultadoUsuario.get(0).getPassword();
                            SimpleEmail email = new SimpleEmail();
                            //email.setDebug(true);
                            //Utilize o hostname do seu provedor de email
                            email.setHostName("smtp.gmail.com");
                            //Quando a porta utilizada não é a padrão (gmail = 465)
                            //email.setSmtpPort(587);
                            //Adicione os destinatários
                            email.addTo(resultadoEmail.get(0).getEmail(), resultadoUsuario.get(0).getNome());
                            //Configure o seu email do qual enviará
                            email.setFrom("pscsgr@gmail.com", "SGR");
                            //Adicione um assunto
                            email.setSubject("Resgatar Credenciais SGR");
                            //Adicione a mensagem do email
                            String msg=new String();
                            msg="Eai"+resultadoUsuario.get(0).getNome()+", fiz isso pra tentar ganhar uns pontos a mais.  ";
                            if(cbxLogin.isSelected())
                                msg+=" Login: "+resultadoUsuario.get(0).getUserName();
                            if(cbxSenha.isSelected())
                                msg+=" Senha: "+resultadoUsuario.get(0).getPassword();
                            email.setMsg(msg);
                            //Para autenticar no servidor é necessário chamar os dois métodos abaixo
                            email.setSSLOnConnect(true);
                            email.setAuthentication("pscsgr@gmail.com", "asdfgh123");
                            email.send();
                            JOptionPane.showMessageDialog(rootPane, "Email com credencial(s) enviado");
                            setClosed(true);
                        } catch (EmailException ex) {
                            Logger.getLogger(Resgatar.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (PropertyVetoException ex) {
                            Logger.getLogger(Resgatar.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
                if(!cadastrado)
                    JOptionPane.showMessageDialog(rootPane, "Nenhum usuario cadastrado com este Email");

            } catch (ViolacaoRegraNegocioException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        } 
        else
            JOptionPane.showMessageDialog(rootPane, "Nenhuma credencial selecionada");
    }//GEN-LAST:event_btnEnviarActionPerformed

    public void centraliza() {
        Dimension d = this.getParent().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JCheckBox cbxLogin;
    private javax.swing.JCheckBox cbxSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
